PRODUCT_VERSION_MAJOR = 0
PRODUCT_VERSION_MINOR = 1

ifeq ($(EXPIDUS_VERSION_APPEND_TIME_OF_DAY),true)
    EXPIDUS_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    EXPIDUS_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set EXPIDUS_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef EXPIDUS_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "EXPIDUS_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^EXPIDUS_||g')
        EXPIDUS_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(EXPIDUS_BUILDTYPE)),)
    EXPIDUS_BUILDTYPE := UNOFFICIAL
    EXPIDUS_EXTRAVERSION :=
endif

ifeq ($(EXPIDUS_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        EXPIDUS_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

EXPIDUS_VERSION_SUFFIX := $(EXPIDUS_BUILD_DATE)-$(EXPIDUS_BUILDTYPE)$(EXPIDUS_EXTRAVERSION)-$(EXPIDUS_BUILD)

# Internal version
EXPIDUS_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(EXPIDUS_VERSION_SUFFIX)

# Display version
EXPIDUS_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(EXPIDUS_VERSION_SUFFIX)
